spring.application.name: generic_erp
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

security:
  cors:
    allowed-origins: http://localhost:5173,http://127.0.0.1:5173,http://198.18.0.1:5173/
  token:
    cookie:
      secure: false
    secret:
      access: test-access-secret-for-junit-only-1234567890
      refresh: test-refresh-secret-for-junit-only-1234567890
    expiracy:
      access: 900000
      refresh: 604800000
logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    web: DEBUG
    "[org.hibernate]": error
